---
minVersion: 0.34.1
github:
  owner: getsentry
  repo: devenv
changelogPolicy: auto
preReleaseCommand: bash ci/bump-version.sh
targets:
  - name: pypi
  - name: sentry-pypi
    internalPypiRepo: getsentry/pypi
