repos:
  - repo: local
    hooks:
      - id: reorder-python-imports
        name: reorder-python-imports
        entry: .venv/bin/reorder-python-imports
        language: system
        types: [python]
        args: [--py311-plus, --add-import, "from __future__ import annotations"]
      - id: black
        name: black
        entry: .venv/bin/black
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: .venv/bin/flake8
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: .venv/bin/mypy
        language: system
        types: [python]
      - id: shellcheck
        name: shellcheck
        entry: .venv/bin/shellcheck
        language: system
        types: [shell]
        args: [--norc]
