#!/bin/bash
shopt -s expand_aliases  # NB: aliases must be defined before bash *parses* any usage
if [[ "$UID" -eq 0 ]]; then
  alias sudo=
fi

set -ex
sudo apt-get update
sudo apt-get install --yes --no-install-recommends "$@"
sudo rm -rf /var/lib/apt/lists/*
