name: install-devenv
on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    # enable xtrace by default
    # use a login shell, to enable ~/.profile
    # the default default is:
    #      bash --noprofile --norc -eo pipefail {0}
    shell: bash --login -eo pipefail -ux {0}

jobs:
  install-devenv:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      DEBUG: 1
      SNTY_DEVENV_BRANCH:
        "${{ github.event.pull_request && github.head_ref || github.ref_name }}"
    steps:
      - uses: actions/checkout@v3
      - name: remove homebrew
        run: |
          df \
              /usr/local/var/homebrew \
              /usr/local/bin/brew /usr/local/Homebrew /usr/local/Cellar /usr/local/Caskroom \
              /usr/local/bin/pydoc* /usr/local/bin/python* /usr/local/bin/2to3* /usr/local/bin/idle3* \
              /usr/local/bin/chromedriver \
            || : "just looking around"
          ls -laF --color /usr/local /usr/local/bin /usr/local/var \
            || : "just looking around"
          uname -s
          uname -m

      - name: install
        run: |
          : should be able to be run from anywhere:
          repo=$PWD
          mv install-devenv.sh /tmp
          cd /tmp
          ./install-devenv.sh  < $repo/ci/install-devenv-checks.sh

      - name: bootstrap sentry
        run: |
          # we don't have permissions to clone getsentry which is a good thing
          # eventually we should move this bootstrap testing over to getsentry repo
          # in the meantime, mock it so that pip install -e has something to chew on
          mkdir -p $HOME/dev/getsentry
          cat <<EOF > $HOME/dev/getsentry/pyproject.toml
          [project]
          name = "getsentry-mock"
          version = "0.0.0"
          EOF

          # note: colima will be used and is necessary for a docker runtime on
          #       macos GitHub runners
          devenv bootstrap

          cd $HOME/dev/sentry
          direnv allow
