name: install-devenv
on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    # enable xtrace by default
    # use an interactive shell, to enable ~/.zshrc
    # the default default is:
    #      bash --noprofile --norc -eo pipefail {0}
    shell: zsh -li {0}
env:
  PYTHONUNBUFFERED: "1"
  DEBUG: "1"

jobs:
  install-devenv:
    runs-on: macos-13
    timeout-minutes: 60
    env:
      SNTY_DEVENV_BRANCH:
        "${{ github.event.pull_request && github.head_ref || github.ref_name }}"
    steps:
      - uses: actions/checkout@v3
      - name: debug info
        run: |
          id

          which python3
          python3 --version
          which ruby
          ruby --version

          pwd
          ls -la
          env | (grep XDG || : grep XDG got no results)

          cat <<'EOF' | tee -a ~/.zshrc ~/.bashrc
          export PS4=$'+ %N\033[1;31m$\033[m '
          set -x
          : top-level GHA shell commands colorized with bold red prompt
          EOF
      - name: remove homebrew
        run: |
          setopt +o nomatch  # continue when glob has no match
          sudo rm -rf \
              /usr/local/var/homebrew \
              /usr/local/bin/brew /usr/local/Homebrew /usr/local/Cellar /usr/local/Caskroom \
              /usr/local/bin/pydoc* /usr/local/bin/python* /usr/local/bin/2to3* /usr/local/bin/idle3* \
              /usr/local/bin/chromedriver \
          ;
      - name: install
        run: |
          set -u
          : should be able to be run from anywhere:
          repo=$PWD
          mv install-devenv.sh /tmp
          cd /tmp
          ./install-devenv.sh  < $repo/ci/install-devenv-checks.sh

      - name: bootstrap sentry
        run: ./ci/devenv-bootstrap.sh
